### ISSUE TITLE
timezoneService  System.TypeInitializationException  ?

### ISSUE THREAD

**Issue by chenkai** [onovotny/WinRTTimeZones#6]
as fllow use it in windows phone : 

IReadOnlyList<string> timeZoneIds= TimeZoneService.SystemTimeZoneIds;
TimeZoneService.FindSystemTimeZoneById("Central Standard Time");
windowsTimeZone = TimeZoneService.FindSystemTimeZoneById(windowsTimeZoneId); 

when get systemTimzeZoneIds got this exception?

**Comment by gordonwatts** [comment]
I am having this exact same error in my test runner (which is a Win 8.1 targeted guy) testing a PCL library.

Looking at references for my PCL, I see the TimeZones, and in the test library I have both TimeZones and TimeZones.Platform.

The only references to TimeZone in the test project are the two .dll's above.

Switching the build to x86 does not seem to affect the results.

Looking at the unpacked package, the .targets file seems to be only for the wp8 profile. This is windows 8.1 store, so perhaps...?

**Comment by onovotny** [comment]
The .targets file is only needed for WP8 because it needs native code to access the underlying Win32 timezone api's. Win81 code doesn't need native code, just P/Invokes.

Which test runner are you using? Can you check if both files are in the bin\<configuration>\AppX dir?

**Comment by gordonwatts** [comment]
My bad, I'm using a PCL, and a test runner that is building under .NET 4.5.1.

When I look at bin/Debug for the test runner, I see TimeZones.dll, TimeZones.Platform.dll, and TimeZones.xml.

**Comment by gordonwatts** [comment]
Oh! Ok, this is weird. The TimeZone.dll file is copied over into the "Out" directory for the test, which is where it is loaded (according to the debugger), but the TimeZones.Platform.dll file is not copied over there. Nor is the XML file. So something weird is going on with the deployment operation at the very least.

**Comment by gordonwatts** [comment]
If I copy by hand the TimeZone.Platform guy over, then it works just fine (it loads it up). So the question boils down to: why doesn't it get deployed to the test directory. I'm afraid I don't understand how .NET test runner works well enough to know the rules. But perhaps because TimeZones.Platform is loaded by hand?

**Comment by onovotny** [comment]
Sorry, not too sure how MSTest works that way...but you could always try using xUnit. It doesn't copy files around. Just add xunit to your test library, use the Fact attributes on your test methods and add the xunit.runner.visualstudio package.

**Comment by gordonwatts** [comment]
I've used xUnit before. I guess I could. I've already got a lot of tests (several hundred), so I don't really relish converting just to get this to work.

**Comment by onovotny** [comment]
There may be a way to tell MStest what to copy; I just don't know...sorry.

**Comment by gordonwatts** [comment]
Yeah, it is called DeploymentItem, and you put it at the top of a test class or method or similar. That is one thing to do. However, it turns out this may not work for me in the end - my data source is using city's to specify the timezones (e.g. Europe/Zurich - which is in the master timezone database - http://www.iana.org/time-zones - I didn't even know this existed before this, it is pretty cool), and at least to first order, WinRTTimeZone isn't getting those back - I assume windows doesn't do it like this, so that is why it is failing.

**Comment by gordonwatts** [comment]
Shoot, I've totally hijacked this thread. You should probably close the issue. :-)

**Comment by onovotny** [comment]
Yeah, Windows has its own time zone id's. They'll need to solve this for the TimeZone functionality in .NET Core as it's cross-plat, but for now I think only NodaTime handles it.

FWIW, .NET Core's TimeZoneInfo class has all of the necessary methods rendering this library moot for UWP.
